/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.farmsystem.view;

import ec.edu.espe.farmsystem.controller.ChickenController;
import ec.edu.espe.farmsystem.model.Chicken;
import javax.swing.JOptionPane;
import utils.FileManager;

/**
 *
 * @author Edison Lascano Hypertech ESPE-DCCO
 */
public class FrmChicken extends javax.swing.JFrame {

    /**
     * Creates new form FrmChicken
     */
    public FrmChicken() {
        initComponents();
        ChickenController chickenController = new ChickenController();
        String[] lines = new String[FileManager.countLines("chickens")];
        Chicken[] chickens = new Chicken[FileManager.countLines("chickens")];
        
        chickenController.read(lines, chickens);
        
        chickenController.populateChickensTable(tblChickens, chickens);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cmbColor = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        cmbIsMolting = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreChickens = new javax.swing.JTextArea();
        btnShowChickens = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChickens = new javax.swing.JTable();
        findChicken = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CHICKENS");

        jLabel2.setText("Name:");

        jLabel3.setText("Color:");

        jLabel4.setText("Age:");

        jLabel5.setText("isMolting");

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "white", "black", "brown", "golden", "yellow", "grey" }));

        cmbIsMolting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));

        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAreChickens.setColumns(20);
        txtAreChickens.setRows(5);
        jScrollPane1.setViewportView(txtAreChickens);

        btnShowChickens.setText("show Chickens");
        btnShowChickens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowChickensActionPerformed(evt);
            }
        });

        tblChickens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Color", "Age", "is Molting"
            }
        ));
        tblChickens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChickensMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblChickens);

        findChicken.setText("Find a Chicken");
        findChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findChickenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbIsMolting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnSave)
                        .addGap(55, 55, 55)
                        .addComponent(btnShowChickens))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(findChicken)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addGap(53, 53, 53)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnShowChickens)
                            .addComponent(findChicken))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(cmbIsMolting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Chicken chicken;
        String name;
        String color;
        int age;
        boolean isMolting;
        ChickenController chickenController = new ChickenController();

        name = txtName.getText();
        color = cmbColor.getSelectedItem().toString();
        age = Integer.parseInt(txtAge.getText());
        isMolting = Boolean.parseBoolean(cmbIsMolting.getSelectedItem().toString());

        chicken = new Chicken(name, color, age, isMolting);

        chickenController.save(chicken);

        JOptionPane.showMessageDialog(rootPane, chicken.getName());

        emptyFields();
        btnShowChickensActionPerformed(evt);
        //chickenController.populateChickensTable(tblChickens, chickens);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnShowChickensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowChickensActionPerformed
        String[] lines = new String[FileManager.countLines("chickens")];
        ChickenController chickenController = new ChickenController();
        Chicken[] chickens = new Chicken[FileManager.countLines("chickens")];

        chickenController.read(lines, chickens);

        for (Chicken chicken : chickens) {
            txtAreChickens.setText(txtAreChickens.getText() + "\n" + chicken.getName());
        }

        chickenController.populateChickensTable(tblChickens, chickens);
    }//GEN-LAST:event_btnShowChickensActionPerformed

    private void findChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findChickenActionPerformed

        String[] lines = new String[FileManager.countLines("chickens")];
        ChickenController chickenController = new ChickenController();
        Chicken[] chickens = new Chicken[FileManager.countLines("chickens")];
        chickenController.read(lines, chickens);
        int index = chickenController.find(chickens, txtName.getText());
        if (index == -1) {
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND", "NOT FOUND", JOptionPane.ERROR_MESSAGE);
        } else {
            tblChickens.setRowSelectionInterval(index, index);
        }

    }//GEN-LAST:event_findChickenActionPerformed

    private void tblChickensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChickensMouseClicked
        int column = 0;
        int row = tblChickens.getSelectedRow();
        String name = tblChickens.getModel().getValueAt(row, column).toString();
        column=1;
        String color = tblChickens.getModel().getValueAt(row, column).toString();
        column=2;
        String age = tblChickens.getModel().getValueAt(row, column).toString();
        column=3;
        String isMolting = tblChickens.getModel().getValueAt(row, column).toString();
        
        txtName.setText(name);
        txtAge.setText(age);
        cmbColor.setSelectedItem(color);
        cmbIsMolting.setSelectedItem(isMolting);

    }//GEN-LAST:event_tblChickensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChicken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChicken().setVisible(true);
            }
        });
    }

    private void emptyFields() {
        txtName.setText("");
        txtAge.setText("");
        cmbColor.setSelectedItem("white");
        cmbIsMolting.setSelectedItem("false");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowChickens;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JComboBox<String> cmbIsMolting;
    private javax.swing.JButton findChicken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblChickens;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextArea txtAreChickens;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
